# Generated by Django 2.1.2 on 2018-11-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20181101_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
            preserve_default=False,
        ),
    ]
