# Generated by Django 2.1.2 on 2018-11-03 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20181101_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='receiver',
            field=models.ForeignKey(on_delete='cascade', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
