# Generated by Django 2.1.2 on 2018-11-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_reply_to'),
        ('comments', '0006_auto_20181103_1515'),
    ]

    operations = [
    ]
